version: "3.9"
services:
  analytics:
    build: ./analytics
    volumes: 
      - "./data:/app/data"
      - "./config.yaml:/app/config.yaml"
    ports: 
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ingestor:
    build: ./ingestor
    volumes: 
      - "./data:/app/data"
      - "./config.yaml:/app/config.yaml"
    depends_on:
      - analytics
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  scheduler:
    build: ./scheduler
    volumes: 
      - "./data:/app/data"
      - "./config.yaml:/app/config.yaml"
    depends_on:
      - analytics
      - ingestor
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    environment:
      - METRICS_API=http://analytics:8000
      - PYTHONPATH=/app
    volumes: 
      - "./data:/app/data"
      - "./config.yaml:/app/config.yaml"
    ports: 
      - "8501:8501"
    depends_on:
      - analytics
    restart: unless-stopped
